export default function(state=null,action){
	return [
                {   
                    "id":1234,
                    "freightBill":{
                        "number":123,
                        "type":"A"
                    },
                    "agency":"ABC",
                    "truckDetails":{
                        "capacity":123
                    },
                    "driver":{
                        "name": "A. BC",
                        "phone1":123,
                        "phone2":123
                    },
                    "operator": "A. BC",
                    "billOfLading":"ABC",
                    "puNumber":123,
                    "dispatcher":{
                        "name":"A. BC",
                        "phone":123
                    },
                    "statuses":[
                        {
                            "type":"ABC",
                            "timestamp":123,
                            "event":"ABC",
                            "location":{
                                "lat":123,
                                "lon":123,
                                "address":"ABC",
                                "address2":"ABC",
                                "city":"ABC",
                                "state":"ABC",
                                "postalCode":123, 
                                "country":"ABC"
                            },
                            "notes":"ABC"
                        },
                        {
                            "type":"ABC",
                            "timestamp":123,
                            "event":"ABC",
                            "location":{
                                "lat":123,
                                "lon":123,
                                "address":"ABC",
                                "address2":"ABC",
                                "city":"ABC",
                                "state":"ABC",
                                "postalCode":123, 
                                "country":"ABC"
                            },
                            "notes":"ABC"
                        },
                        {
                            "type":"ABC",
                            "timestamp":123,
                            "event":"ABC",
                            "location":{
                                "lat":123,
                                "lon":123,
                                "address":"ABC",
                                "address2":"ABC",
                                "city":"ABC",
                                "state":"ABC",
                                "postalCode":123, 
                                "country":"ABC"
                            },
                            "notes":"ABC"
                        }
                    ],
                    "loadInstructions":{
                        "author":"A. BC",
                        "phone":123,
                        "notes":"ABC"
                    },
                    "stops":[
                        {
                            "order":1,
                            "timestamp":123,
                            "address":"ABC",
                            "address2":"ABC",
                            "city":"ABC",
                            "state":"ABC",
                            "postalCode":123,
                            "country":"ABC",
                            "lat":123,
                            "lon":123,
                            "arrivalTime":123,
                            "departureTime":123,
                            "trailerDropped":123,
                            "trailerPickedUp":123,
                            "nextFreightBillNumber":123,
                            "deliveryUpdated":"bool",
                            "departureUpdated":"bool",
                            "losmDepature":"bool",
                            "losmArrival":"bool",
                            "notes":"ABC"
                        },
                        {
                            "order":2,
                            "timestamp":123,
                            "address":"ABC",
                            "address2":"ABC",
                            "city":"ABC",
                            "state":"ABC",
                            "postalCode":123,
                            "country":"ABC",
                            "lat":123,
                            "lon":123,
                            "arrivalTime":123,
                            "departureTime":123,
                            "trailerDropped":123,
                            "trailerPickedUp":123,
                            "nextFreightBillNumber":123,
                            "deliveryUpdated":"bool",
                            "departureUpdated":"bool",
                            "losmDepature":"bool",
                            "losmArrival":"bool",
                            "notes":"ABC"


                        }
                    ],
                    "notes":[
                        {
                            "author":"ABC",
                            "timestamp":123,
                            "content":"ABC"
                        },
                        {
                            "author":"ABC",
                            "timestamp":123,
                            "content":"ABC"
                        },
                        {
                            "author":"ABC",
                            "timestamp":123,
                            "content":"ABC"
                        }
                    ],
                    "updateTimes":[
                        {
                            "timestamp":123,
                            "tasks":[
                                "ABC",
                                "DEF",
                                "GHI"
                                ]
                        },
                        {
                            "timestamp":123,
                            "tasks":[
                                "ABC",
                                "DEF",
                                "GHI"
                                ]
                        },
                        {
                            "timestamp":123,
                            "tasks":[
                                "ABC",
                                "DEF",
                                "GHI"
                                ]
                        }
                    ],
                    "history":[
                        {
                            "timestamp":123,
                            "type":"ABC",
                            "author":"A. BC",
                        },
                        {
                            "timestamp":123,
                            "type":"ABC",
                            "author":"A. BC",
                        },
                        {
                            "timestamp":123,
                            "type":"ABC",
                            "author":"A. BC",
                        }
                    ],
                    "issues":[
                        {
                            "timestamp":123,
                            "type":"ABC",
                            "notes":"ABC",
                            "author":"A. BC"
                        },
                         {
                            "timestamp":123,
                            "type":"ABC",
                            "notes":"ABC",
                            "author":"A. BC"
                        },
                         {
                            "timestamp":123,
                            "type":"ABC",
                            "notes":"ABC",
                            "author":"A. BC"
                        }
                    ],
                    "tracking":{
                        "truckerTools":{
                            "loadExternalId":123
                        },
                        "landstarConnect":{
                            "loadId":123
                        }
                    },
                    "settings":{
                        "freightBill":{
                            "required":"bool",
                            "color":123,
                            "helpText":"ABC"

                        },
                        "status":{
                            "required":"bool",
                            "color":123,
                            "isTruckerTools":"bool",
                            "isLandstar":"bool",
                            "helpText":"ABC"
                        },
                        "loadInstructions":{
                            "required":"bool",
                            "color":123,
                            "helpText":"ABC"
                        },
                        "shipperDetails":{
                            "required":"bool",
                            "color":123,
                            "helpText":"ABC",
                            "requireTrailerNumberPickup":"bool",
                            "requireTrailerNumberDropped":"bool",
                            "requireUpdateTrailerInFreightBill":"bool",
                            "requireLOSM":"bool",
                            "requireCustomerSystem":"bool",
                            "requireExworks":"bool"

                        },
                        "shipperDetails":{
                            "required":"bool",
                            "color":123,
                            "helpText":"ABC",
                            "requireTrailerNumberPickup":"bool",
                            "requireTrailerNumberDropped":"bool",
                            "requireLOSM":"bool",
                            "requireCustomerSystem":"bool",
                            "requireExworks":"bool"

                        },
                        "notes":{
                            "required":"bool",
                            "color":123,
                            "helpText":"ABC",
                        },
                        "tracking":{
                            "required":"bool",
                            "color":123,
                            "helpText":"ABC"
                        },
                        "updates":{
                            "required":"bool",
                            "color":123,
                            "helpText":"ABC"
                        }

                    }
                }
            ];
}

